[versions]
agp = "8.10.0"
android-compileSdk = "36"
jdkAndroid = "11"
jdkDesktop = "21"
android-minSdk = "24"
android-targetSdk = "35"
android-buildtools = "36.0.0"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-core-ktx = "1.16.0"
androidx-annotation = "1.9.1"
androidx-espresso-core = "3.6.1"
androidx-lifecycle = "2.8.4"
jetbrains-lifecycle = "2.8.4"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
compose-multiplatform = "1.8.1"
junit = "4.13.2"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.1"
kotlinx-datetime = "0.6.2"
ktor = "3.1.3"
kotlin = "2.1.20"
ktorfit = "2.5.1"
google-ksp = "2.1.20-1.0.32"
detekt = "1.23.8"
compose-rules = "0.4.22"
ktlint = "1.5.0"
manifestGuard = "1.0.0"
koin = "4.0.4"


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
jetbrains-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }
jetbrains-compose-uiTooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }

kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

ktorfit = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib-light", version.ref = "ktorfit" }
ktorfit-converters-response = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-response", version.ref = "ktorfit" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-engine-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-engine-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-engine-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-client-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

gradleplugins-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradleplugins-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradleplugins-kotlinxSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
gradleplugins-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
gradleplugins-composeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradleplugins-detekt = { module = "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }

detektPlugin-nlopez-composeRules = { module = "io.nlopez.compose.rules:detekt", version.ref = "compose-rules" }

ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

# KOIN
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }

koin-test = { module = "io.insert-koin:koin-test" }

koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }

koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

jetbrains-compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp"}

ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

manifestGuard = { id = "com.dpforge.manifestguard", version.ref = "manifestGuard" }

## Gradle scripts from the project
arabicdict-detekt = { id = "dev.arabicdictionary.pro.detekt" }
arabicdict-ktlint = { id = "dev.arabicdictionary.pro.ktlint" }

arabicdict-android-base = { id = "dev.arabicdictionary.pro.android.base" }
arabicdict-android-library = { id = "dev.arabicdictionary.pro.android.library" }

arabicdict-compose-base = { id = "dev.arabicdictionary.pro.jetbrains-compose.base" }
arabicdict-compose-android = { id = "dev.arabicdictionary.pro.jetbrains-compose.android" }
arabicdict-compose-desktop = { id = "dev.arabicdictionary.pro.jetbrains-compose.desktop" }
arabicdict-compose-ios = { id = "dev.arabicdictionary.pro.jetbrains-compose.ios" }
arabicdict-compose = { id = "dev.arabicdictionary.pro.jetbrains-compose.all" }
arabicdict-compose-jetpack-base = { id = "dev.arabicdictionary.pro.jetpack-compose.base" }

arabicdict-kmplib-base = { id = "dev.arabicdictionary.pro.kmp.library.base" }
arabicdict-kmplib-android = { id = "dev.arabicdictionary.pro.kmp.library.android" }
arabicdict-kmplib-desktop = { id = "dev.arabicdictionary.pro.kmp.library.desktop" }
arabicdict-kmplib-ios = { id = "dev.arabicdictionary.pro.kmp.library.ios" }
arabicdict-kmplib = { id = "dev.arabicdictionary.pro.kmp.library.all" }